//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionDetail
    {
        public int ID { get; set; }
        public int IDPrescription { get; set; }
        public int IDMedicine { get; set; }
        public int Quantity { get; set; }
        public int Morning { get; set; }
        public int Noon { get; set; }
        public int Afternoon { get; set; }
        public int Night { get; set; }
        public string Using { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
